### ISSUE TITLE
Filtering graphtyper output results in losing 98% of SVs

### ISSUE THREAD

**Issue by dr-ashu-geno** [DecodeGenetics/graphtyper#90] opened 2021-09-30 03:26 UTC
Hello @hannespetur. Thank you for developing such a nice program. 

I used Manta to call SVs in a large number of human genome samples (aligned to hg38) and got the union of SVs using svimmer which resulted in **451,176** SVs. Then, I genotyped samples in batches (1000 samples per batch). Then, I merged the graphtyper outputs of all batches. However, after filtering graphtyper results using vcflib with the exact command used in graphtyper paper, only **9,000** SVs remain in output file. This is the command I use for filtering:

$VCFLIB vcffilter -f "( SVTYPE = BND & SVMODEL = AGGREGATED & QD > 20 & ( ABHet > 0.30 | ABHet < 0 ) & ( AC / NUM_MERGED_SVS ) < 10 & PASS_AC > 0 & PASS_ratio > 0.1 ) | ( SVTYPE = DEL & SVMODEL = AGGREGATED & QD > 12 & ( ABHet > 0.30 | ABHet < 0 ) & ( AC / NUM_MERGED_SVS ) < 25 & PASS_AC > 0 & PASS_ratio > 0.1 ) | ( SVTYPE = DUP & SVMODEL = AGGREGATED & QD > 5 & PASS_AC > 0 & ( AC / NUM_MERGED_SVS ) < 25 ) | ( SVTYPE = INS & SVMODEL = AGGREGATED & PASS_AC > 0 & ( AC / NUM_MERGED_SVS ) < 25 & PASS_ratio > 0.1 & ( ABHet > 0.25 | ABHet < 0 ) & MaxAAS > 4 ) | ( SVTYPE = INV & PASS_AC > 0 & ( AC / NUM_MERGED_SVS ) < 25 & PASS_ratio > 0.1 & ( ABHet > 0.25 | ABHet < 0 ) & MaxAAS > 4 )" input.vcf > output.vcf

Could you please kindly help me with this? I don’t understand where my mistake is that causes losing most of the SVs. 

Thank you in advance.

**Comment by hannespetur** [comment] 2021-09-30 08:57
Hello @dr-ashu-geno sure I will try to help,

The vcflib filter looks good to me. Can you tell me the graphtyper version, the graphtyper genotype_sv command and and graphtyper merge commands you used? 

If you can share portion of the merged output file (before filtering) this would also help me try to spot something that doesn't look right.


Best,
Hannes

**Comment by dr-ashu-geno** [comment] 2021-09-30 09:44
Dear @hannespetur 
Thank you so much for your prompt reply.

Sure, graphtyper version is 2.7.1.
The number of samples is 11,000.

The graphtyper genotype_sv command is:
./graphtyper genotype_sv $reference_genome $svimmer_output --sams crams_list.txt --force_no_filter_zero_qual --threads=8 --output $OUTDIR --region=$region --max_files_open=32 --avg_cov_by_readlen=$avg_cvg_lngth

For merging graphtyper results I first concatenated the output for each batch using the following command:
$BCFTOOLS concat --file-list $file_list -Oz > $OUTDIR/$ID.samples.bcf

Then I merged outputs of previous step for all batches to a single file using the following command:
$BCFTOOLS merge -m id --file-list $file_list -Oz > $OUTDIR/All-samples-SVs-by-MANTA.bcf

And then, I filtered the final output file using vcflib. 
I attach a part of output file before filtering here. 

Thank you again. 
<img width="1390" alt="Screen Shot 2021-09-30 at 18 39 01" src="https://user-images.githubusercontent.com/91646047/135428910-3896be2f-2a5c-4006-a96d-ba8f40d307be.png">

**Comment by hannespetur** [comment] 2021-09-30 12:55
Thank you for the reply. I think the problem is the bcftools merging because that command doesn't update the INFO fields (understandibly, of course bcftools doesn't know how the graphtyper INFO fields work). Can you instead try

```
graphtyper vcf_merge --sv --file_list=$file_list --output=$OUTDIR/merged.vcf.gz
```

The command assumes that all input files have the exact same order of graphtyper SVs. I see you used `--force_no_filter_zero_qual` so I this should already be the case.

Also, graphtyper does not support bcf so you will need to convert the files from the previous step to vcf.gz.

Best,
Hannes

**Comment by dr-ashu-geno** [comment] 2021-10-06 02:05
Dear @hannespetur 

Thank you so much for your quick reply. Now, the problem is solved. I merged the files using graphtyper which took 14 hours and then filtered the results by BCFtools (which took 30 hours) resulting in 157,000 remaining SVs [Long time is because of large number of samples of course]. 

Thank you for your kind help. 
I think we can close this issue now. 

Best,

**Closed** 2021-10-18 08:44 UTC

**Comment by dr-ashu-geno** [comment] 2024-10-29 02:44
@SunWinner01 
Hi
I don't recommend you use SURVIVOR! I used it several times and observed that the results change if I change the order of the input VCF files! Instead, I recommend you use svimmer.
If you have run MANTA on each of your samples, this is what I did:
I ran svimmer --join-mode for each sample to get the union of SV sites in each sample
Then, I ran svimmer (not --join-mode this time as it is not needed) on all samples to get the union of SV sites in all samples.

Then, I used GraphTyper to do genotyping in all samples by dividing them into 1000-sample batches, running genotyping in each batch, and then merging the genotyping results as mentioned in the above messages as you saw.

Hope it helps,
let me know if you have any questions..
S.

**Comment by SunWinner01** [comment] 2024-10-29 02:52
Thank you very much for your reply. I had noticed this software before, and I will give it a try. @dr-ashu-geno

**Comment by SunWinner01** [comment] 2024-11-18 13:57
你好你好。我已经合并完啦。目前在进行后续的群体分析。我们可以一起讨论！ @kunmonster

**Comment by kunmonster** [comment] 2024-11-18 14:00
> 你好你好。我已经合并完啦。目前在进行后续的群体分析。我们可以一起讨论！ @kunmonster

@SunWinner01 我邮箱fengkunjiang@email.swu.edu.cn方便的话可以来个邮件，这样邮件交流，谢谢

**Comment by dr-ashu-geno** [comment] 2024-11-20 21:16
@SunWinner01 @kunmonster 
May I join your discussion too? 😅 
I would like to know more.. specially about the tools you used for SV calling.

**Comment by kunmonster** [comment] 2024-11-21 00:50
@dr-ashu-geno Sure,but we have exchanged other contact as talking in issue is a little convenient.If u want to join us , providing a email or other.

**Comment by likailong520** [comment] 2024-12-11 05:31
Hello, this is my Google email: lkailong652@gmail.com. Can I join your discussion?

**Comment by likailong520** [comment] 2024-12-11 05:32
> 当然可以，但我们已经交换了其他联系方式，因为有问题的交谈有点不方便。如果您想加入我们，请提供电子邮件或其他。

Hello, this is my Google email: lkailong652@gmail.com. Can I join your discussion?

**Comment by Sreelekshmi-291** [comment] 2025-04-19 12:38
> I ran svimmer --join-mode for each sample to get the union of SV sites in each sample

Hi @dr-ashu-geno 
I understand that you used svimmer --join-mode for each sample to generate the union of SV sites within that sample.
Could you please explain this step in more detail, if possible?

I believe the intention here was to merge nearby SVs within a single sample before performing the multi-sample merge.
Then, I assume you used those "per-sample union VCFs" as input to a second svimmer run across all samples to produce a final merged VCF?

Also, how exactly did you run the --join-mode command? Did you provide the same sample VCF twice to svimmer in that step?
