### ISSUE TITLE
cmake cannot find pthread

### ISSUE THREAD

**Issue by ekg** [DecodeGenetics/graphtyper#9] opened 2018-02-14 10:25 UTC
I'm having trouble building graphtyper:

```text
Determining if the pthread_create exist failed with the following output:
Change Dir: /lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/release-build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a4ad3/fast"
/usr/bin/make -f CMakeFiles/cmTC_a4ad3.dir/build.make CMakeFiles/cmTC_a4ad3.dir/build
make[1]: Entering directory `/lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/release-build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a4ad3.dir/CheckSymbolExists.c.o
/nfs/users/nfs_e/eg10/graphs/bin/gcc    -o CMakeFiles/cmTC_a4ad3.dir/CheckSymbolExists.c.o   -c /lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/release-build
/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_a4ad3
/lustre/scratch115/realdata/mdt3/projects/graphs/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a4ad3.dir/link.txt --verbose=1
/nfs/users/nfs_e/eg10/graphs/bin/gcc       CMakeFiles/cmTC_a4ad3.dir/CheckSymbolExists.c.o  -o cmTC_a4ad3 -rdynamic
CMakeFiles/cmTC_a4ad3.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [cmTC_a4ad3] Error 1
make[1]: Leaving directory `/lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/release-build/CMakeFiles/CMakeTmp'
make: *** [cmTC_a4ad3/fast] Error 2
```

It seems that cmake can't find pthread, but I apparently have it on my system. Has anyone else run into this problem?

**Comment by hannespetur** [comment] 2018-02-14 12:06
Hey Erik,

I haven't seen this problem before. Seems to be CMake related issue since the `CheckSymbolExists.c` file is generated by CMake. Which version of `cmake` are you using? I want to see if I can reproduce the problem with the same version.

All the best,
Hannes

**Comment by ekg** [comment] 2018-02-14 12:55
I'm on 3.3.0-rc2:

```
-> % cmake --version
cmake version 3.3.0-rc2
```

The CheckSymbolExists.c file contains:

```
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

Indeed, I cannot compile it using the command that CMake is giving:

```
/nfs/users/nfs_e/eg10/graphs/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_a46c4.dir/CheckFunctionExists.c.o  -o cmTC_a46c4 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
```

I reproduce this:

```
-> % gcc -DCHECK_FUNCTION_EXISTS=pthread_create -o x.o x.c -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
```

But I can compile it as follows:

```
-> % gcc -DCHECK_FUNCTION_EXISTS=pthread_create -o x.o x.c -rdynamic -lpthread
```

Why would it be looking for `lpthreads`? That doesn't seem to be the correct name of the library. This is relevant: https://stackoverflow.com/questions/37967086/usr-bin-ld-cannot-find-lpthreads. I'll dig around in the CMakeLists.txt to see where it's defined this way.

**Comment by ekg** [comment] 2018-02-14 13:00
`lpthreads` seems to be referred to in ./sparsehash/m4/acx_pthread.m4. Is that somehow used during the cmake setup? It's apparently a solaris thing.

Maybe the setup in CMakeLists.txt is not specific enough:

```
# Find a threads (which will be pthreads on unix)
find_package(Threads)
```

**Comment by hannespetur** [comment] 2018-02-14 13:30
Thank you for looking into this thoroughly. No `/sparsehash/m4/acx_pthread.m4` should not be used during cmake setup. I installed cmake3.3-rc2 but I was able to build graphtyper without problems using that version. However, looking into CMakeFiles/CMakeError.log I see similar errors as you:

```
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/hannese/graphtyper/build/CMakeFiles/CMakeTmp

Run Build Command:"/opt/rh/devtoolset-6/root/usr/bin/gmake" "cmTC_91e76/fast"
/opt/rh/devtoolset-6/root/usr/bin/gmake -f CMakeFiles/cmTC_91e76.dir/build.make CMakeFiles/cmTC_91e76.dir/build
gmake[1]: Entering directory '/home/hannese/graphtyper/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_91e76.dir/CheckSymbolExists.c.o
/opt/rh/devtoolset-6/root/usr/bin/gcc    -o CMakeFiles/cmTC_91e76.dir/CheckSymbolExists.c.o   -c /home/hannese/graphtyper/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_91e76
/home/hannese/Downloads/cmake-3.8.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_91e76.dir/link.txt --verbose=1
/opt/rh/devtoolset-6/root/usr/bin/gcc      -rdynamic CMakeFiles/cmTC_91e76.dir/CheckSymbolExists.c.o  -o cmTC_91e76 
CMakeFiles/cmTC_91e76.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_91e76.dir/build.make:97: recipe for target 'cmTC_91e76' failed
gmake[1]: *** [cmTC_91e76] Error 1
gmake[1]: Leaving directory '/home/hannese/graphtyper/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_91e76/fast' failed
gmake: *** [cmTC_91e76/fast] Error 2
```

I checked in my original build directory and these errors also appear there. So it seems they are excpected.

What I think is happening internally in CMake when `find_packages(Threads)` is called is that it is checking whether it should use the flag `-lpthread`, `-lpthreads` or simply skip the flag in case it is not needed.

Are there any other errors in your CMakeError.log? If not, maybe the configuring was successful and you are able to run `make` in the `release-build`.


All the best,
Hannes

**Comment by ekg** [comment] 2018-02-14 14:15
This is the only error, and yet I am not able to run make... the makefile has not been made.

Which versions of CMake work? It looks like this might be a bug in the specific release candidate I'm using and possibly I should upgrade or downgrade.

**Comment by hannespetur** [comment] 2018-02-14 15:49
I am using CMake 3.8.2 on my personal computer and 2.8.12 at work, these two should at least work. But would be surprised if that is problem since I was able to use CMake 3.3-rc2 without any problems. Does the output of the `cmake ..` not reveal anything unusual? Here is my output when using CMake 3.3-rc2 

```
» /home/hannese/apps/cmake-3.3.0-rc2/my_build/bin/cmake ..                          
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/gcc
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/g++
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: 
-- Building in release mode.
-- CXX flags are: -Wall -Wextra -Wfatal-errors -pedantic -Wno-variadic-macros -std=c++11 -DSEQAN_HAS_ZLIB=1 -DSEQAN_USE_HTSLIB=1 -DSEQAN_ENABLE_TESTING=0 -march=core2 -mtune=generic -O3 -DNDEBUG -DSEQAN_ENABLE_DEBUG=0
-- Checking for zlib
-- Found ZLIB: /home/hannese/miniconda3/lib/libz.so (found version "1.2.11") 
-- Checking for bzip2
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- Checking for Boost
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   iostreams
--   log
--   thread
--   serialization
--   filesystem
-- snappy target location is /home/hannese/graphtyper_cmake33rc2/snappy/.libs/libsnappy.a
-- htslib target location is /home/hannese/graphtyper_cmake33rc2/htslib/libhts.a
-- StatGen target location is /home/hannese/graphtyper_cmake33rc2/statgen/libStatGen.a
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using GCC
-- Could NOT find LZ4 (missing:  LZ4_LIBRARY LZ4_INCLUDE_DIR LZ4_GOOD_VERSION) 
-- Using third-party bundled LZ4
-- Looking for lzma_auto_decoder in /home/hannese/miniconda3/lib/liblzma.so
-- Looking for lzma_auto_decoder in /home/hannese/miniconda3/lib/liblzma.so - found
-- Looking for lzma_easy_encoder in /home/hannese/miniconda3/lib/liblzma.so
-- Looking for lzma_easy_encoder in /home/hannese/miniconda3/lib/liblzma.so - found
-- Looking for lzma_lzma_preset in /home/hannese/miniconda3/lib/liblzma.so
-- Looking for lzma_lzma_preset in /home/hannese/miniconda3/lib/liblzma.so - found
-- Found LibLZMA: /home/hannese/miniconda3/include (found version "5.2.3") 
-- Libraries: rocksdb;snappy;htslib;statgen;/usr/local/lib/libboost_system.a;/usr/local/lib/libboost_iostreams.a;/usr/local/lib/libboost_log.a;/usr/local/lib/libboost_thread.a;/usr/local/lib/libboost_serialization.a;/usr/local/lib/libboost_filesystem.a;pthread;/home/hannese/miniconda3/lib/libz.so;/usr/lib64/libbz2.so;rt;/home/hannese/miniconda3/lib/liblzma.so
-- Compiling graphtyper's source files
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hannese/graphtyper_cmake33rc2/build
```

Best,
Hannes

**Comment by ekg** [comment] 2018-02-14 16:46
Here's my cmake output;

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /nfs/users/nfs_e/eg10/graphs/bin/gcc
-- Check for working C compiler: /nfs/users/nfs_e/eg10/graphs/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nfs/users/nfs_e/eg10/graphs/bin/g++
-- Check for working CXX compiler: /nfs/users/nfs_e/eg10/graphs/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type:
-- Building in release mode.
-- CXX flags are: -Wall -Wextra -Wfatal-errors -pedantic -Wno-variadic-macros -std=c++11 -DSEQAN_HAS_ZLIB=1 -DSEQAN_USE_HTSLIB=1 -DSEQAN_ENABLE_TESTING=0 -march=core2 -mtune=generic -lpthread -O3 -DNDEBUG -DSEQAN_ENABLE_DEBUG=0
-- Checking for zlib
-- Found ZLIB: /nfs/users/nfs_e/eg10/graphs/lib/libz.so (found version "1.2.3.4")
-- Checking for bzip2
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found
-- Checking for Boost
CMake Error at /lustre/scratch115/realdata/mdt3/projects/graphs/share/cmake-3.3/Modules/FindBoost.cmake:1245 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.48.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.57 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:94 (find_package)


-- snappy target location is /lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/snappy/.libs/libsnappy.a
-- htslib target location is /lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/htslib/libhts.a
-- StatGen target location is /lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/statgen/libStatGen.a
-- Using GCC
-- Performing Test LZ4_GOOD_VERSION
-- Performing Test LZ4_GOOD_VERSION - Success
-- Found LZ4: /nfs/users/nfs_e/eg10/graphs/lib/liblz4.so
-- Found LZ4: /nfs/users/nfs_e/eg10/graphs/lib/liblz4.so
-- Looking for lzma_auto_decoder in /nfs/users/nfs_e/eg10/graphs/lib/liblzma.so
-- Looking for lzma_auto_decoder in /nfs/users/nfs_e/eg10/graphs/lib/liblzma.so - found
-- Looking for lzma_easy_encoder in /nfs/users/nfs_e/eg10/graphs/lib/liblzma.so
-- Looking for lzma_easy_encoder in /nfs/users/nfs_e/eg10/graphs/lib/liblzma.so - found
-- Looking for lzma_lzma_preset in /nfs/users/nfs_e/eg10/graphs/lib/liblzma.so
-- Looking for lzma_lzma_preset in /nfs/users/nfs_e/eg10/graphs/lib/liblzma.so - found
-- Found LibLZMA: /nfs/users/nfs_e/eg10/graphs/include (found version "5.2.3")
-- Libraries: rocksdb;snappy;htslib;statgen;/nfs/users/nfs_e/eg10/graphs/lib/libz.so;/usr/lib/x86_64-linux-gnu/libbz2.so;rt;/nfs/users/nfs_e/eg10/graphs/lib/liblz4.so;/nfs/users/nfs_e/eg10/graphs/lib/liblzma.so
-- Compiling graphtyper's source files
-- Configuring incomplete, errors occurred!
See also "/lustre/scratch115/realdata/mdt3/projects/graphs/graphtyper/build/CMakeFiles/CMakeOutput.log".
```

The output log: 
[c.log.txt](https://github.com/DecodeGenetics/graphtyper/files/1724878/c.log.txt)

**Comment by ekg** [comment] 2018-02-14 16:47
Ah, sorry, there is also the issue of the boost libraries. I have them in a custom location so I need to tell cmake where to look for them. Let me see if that helps.

**Comment by ekg** [comment] 2018-02-14 16:48
OK! This appears to have resolved the problem:

```bash
cmake -DBOOST_ROOT=~/graphs/src/boost_1_64_0 ..
```

Excuse the noise! I'm compiling now.

**Comment by ekg** [comment] 2018-02-14 16:49
And things may still be complicated as I'd made modifications to the CMakeLists.txt. I'll post if setting the boost root isn't enough to resolve the problem. Otherwise I'll close the issue.

**Closed** 2018-02-14 16:53 UTC

**Comment by hannespetur** [comment] 2018-02-14 16:57
Great to hear you figured out the problem. Let me know if you encounter any other issues.

All the best,
Hannes

**Comment by ekg** [comment] 2018-02-14 17:20
Thanks for the help Hannes!

**Comment by AchalaSB** [comment] 2018-08-20 06:18
achala@laptop:~/GIT/mir2wasm$ cargo build
   Compiling mir2wasm v0.1.0 (file:///home/achala/GIT/mir2wasm)
error: failed to run custom build command for `mir2wasm v0.1.0 (file:///home/achala/GIT/mir2wasm)`
process didn't exit successfully: `/home/achala/GIT/mir2wasm/target/debug/build/mir2wasm-4f880614b2dd408e/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/achala/GIT/mir2wasm/binaryen" "-DBUILD_STATIC_LIB=ON" "-DCMAKE_INSTALL_PREFIX=/home/achala/GIT/mir2wasm/target/debug/build/mir2wasm-cadbd25f2f277410/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC-m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Building with -std=c++11
-- Building with -msse2
-- Building with -mfpmath=sse
-- Building with -Wall
-- Building with -Werror
-- Building with -Wextra
-- Building with -Wno-unused-parameter
-- Building with -fno-omit-frame-pointer
-- Building with -fPIC
-- Building with -O0
-- Building with -g3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/achala/GIT/mir2wasm/target/debug/build/mir2wasm-cadbd25f2f277410/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
[  7%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o
[  7%] Building CXX object src/asmjs/CMakeFiles/asmjs.dir/shared-constants.cpp.o
[ 14%] Built target wasm
[ 14%] Built target ast
[ 15%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/parser.cpp.o
[ 56%] Built target passes
[ 57%] Building CXX object src/support/CMakeFiles/support.dir/threads.cpp.o
src/asmjs/CMakeFiles/asmjs.dir/build.make:86: recipe for target 'src/asmjs/CMakeFiles/asmjs.dir/shared-constants.cpp.o' failed
CMakeFiles/Makefile2:430: recipe for target 'src/asmjs/CMakeFiles/asmjs.dir/all' failed
src/support/CMakeFiles/support.dir/build.make:206: recipe for target 'src/support/CMakeFiles/support.dir/threads.cpp.o' failed
CMakeFiles/Makefile2:595: recipe for target 'src/support/CMakeFiles/support.dir/all' failed
src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/build.make:86: recipe for target 'src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/parser.cpp.o' failed
src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/build.make:62: recipe for target 'src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o' failed
CMakeFiles/Makefile2:485: recipe for target 'src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/all' failed
Makefile:129: recipe for target 'all' failed

--- stderr
In file included from /home/achala/GIT/mir2wasm/binaryen/src/emscripten-optimizer/istring.h:32:0,
                 from /home/achala/GIT/mir2wasm/binaryen/src/asmjs/shared-constants.h:20,
                 from /home/achala/GIT/mir2wasm/binaryen/src/asmjs/shared-constants.cpp:17:
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:51:8: error: ‘function’ in namespace ‘std’ does not name a template type
   std::function<ThreadWorkState ()> doWork = nullptr;
        ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:59:18: error: ‘std::function’ has not been declared
   void work(std::function<ThreadWorkState ()> doWork);
                  ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:59:26: error: expected ‘,’ or ‘...’ before ‘<’ token
   void work(std::function<ThreadWorkState ()> doWork);
                          ^
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: error: ‘function’ is not a member of ‘std’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: note: suggested alternative: ‘is_function’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
                              is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: error: ‘function’ is not a member of ‘std’
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: note: suggested alternative: ‘is_function’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
                              is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:56: error: template argument 1 is invalid
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                                                        ^
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:56: error: template argument 2 is invalid
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:57: error: expected ‘,’ or ‘...’ before ‘>’ token
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                                                         ^~
In file included from /home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:23:0:
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:51:8: error: ‘function’ in namespace ‘std’ does not name a template type
   std::function<ThreadWorkState ()> doWork = nullptr;
        ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:59:18: error: ‘std::function’ has not been declared
   void work(std::function<ThreadWorkState ()> doWork);
                  ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:59:26: error: expected ‘,’ or ‘...’ before ‘<’ token
   void work(std::function<ThreadWorkState ()> doWork);
                          ^
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: error: ‘function’ is not a member of ‘std’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: note: suggested alternative: ‘is_function’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
                              is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: error: ‘function’ is not a member of ‘std’
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: note: suggested alternative: ‘is_function’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
                              is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:56: error: template argument 1 is invalid
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                                                        ^
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:56: error: template argument 2 is invalid
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:57: error: expected ‘,’ or ‘...’ before ‘>’ token
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                                                         ^~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:65:24: error: variable or field ‘work’ declared void
 void Thread::work(std::function<ThreadWorkState ()> doWork_) {
                        ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:65:24: error: ‘function’ is not a member of ‘std’
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:65:24: note: suggested alternative: ‘is_function’
 void Thread::work(std::function<ThreadWorkState ()> doWork_) {
                        ^~~~~~~~
                        is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:65:53: error: ‘doWork_’ was not declared in this scope
 void Thread::work(std::function<ThreadWorkState ()> doWork_) {
                                                     ^~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp: In static member function ‘static void wasm::Thread::mainLoop(void*)’:
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:83:17: error: ‘class wasm::Thread’ has no member named ‘doWork’; did you mean ‘work’?
       if (self->doWork) {
                 ^~~~~~
                 work
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:86:22: error: ‘class wasm::Thread’ has no member named ‘doWork’; did you mean ‘work’?
         while (self->doWork() == ThreadWorkState::More) {}
                      ^~~~~~
                      work
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:87:15: error: ‘class wasm::Thread’ has no member named ‘doWork’; did you mean ‘work’?
         self->doWork = nullptr;
               ^~~~~~
               work
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:96:33: error: ‘class wasm::Thread’ has no member named ‘doWork’; did you mean ‘work’?
       if (!self->done && !self->doWork) {
                                 ^~~~~~
                                 work
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp: At global scope:
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:40: error: ‘function’ is not a member of ‘std’
 void ThreadPool::work(std::vector<std::function<ThreadWorkState ()>>& doWorkers) {
                                        ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:40: note: suggested alternative: ‘is_function’
 void ThreadPool::work(std::vector<std::function<ThreadWorkState ()>>& doWorkers) {
                                        ^~~~~~~~
                                        is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:40: error: ‘function’ is not a member of ‘std’
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:40: note: suggested alternative: ‘is_function’
 void ThreadPool::work(std::vector<std::function<ThreadWorkState ()>>& doWorkers) {
                                        ^~~~~~~~
                                        is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:66: error: template argument 1 is invalid
 void ThreadPool::work(std::vector<std::function<ThreadWorkState ()>>& doWorkers) {
                                                                  ^
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:66: error: template argument 2 is invalid
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:28: error: variable or field ‘work’ declared void
 void ThreadPool::work(std::vector<std::function<ThreadWorkState ()>>& doWorkers) {
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.cpp:137:71: error: ‘doWorkers’ was not declared in this scope
 void ThreadPool::work(std::vector<std::function<ThreadWorkState ()>>& doWorkers) {
                                                                       ^~~~~~~~~
make[2]: *** [src/asmjs/CMakeFiles/asmjs.dir/shared-constants.cpp.o] Error 1
make[1]: *** [src/asmjs/CMakeFiles/asmjs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/achala/GIT/mir2wasm/binaryen/src/emscripten-optimizer/istring.h:32:0,
                 from /home/achala/GIT/mir2wasm/binaryen/src/emscripten-optimizer/parser.h:31,
                 from /home/achala/GIT/mir2wasm/binaryen/src/emscripten-optimizer/parser.cpp:17:
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:51:8: error: ‘function’ in namespace ‘std’ does not name a template type
   std::function<ThreadWorkState ()> doWork = nullptr;
        ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:59:18: error: ‘std::function’ has not been declared
   void work(std::function<ThreadWorkState ()> doWork);
                  ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:59:26: error: expected ‘,’ or ‘...’ before ‘<’ token
   void work(std::function<ThreadWorkState ()> doWork);
                          ^
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: error: ‘function’ is not a member of ‘std’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: note: suggested alternative: ‘is_function’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
                              is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: error: ‘function’ is not a member of ‘std’
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:30: note: suggested alternative: ‘is_function’
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                              ^~~~~~~~
                              is_function
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:56: error: template argument 1 is invalid
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                                                        ^
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:56: error: template argument 2 is invalid
/home/achala/GIT/mir2wasm/binaryen/src/support/threads.h:93:57: error: expected ‘,’ or ‘...’ before ‘>’ token
   void work(std::vector<std::function<ThreadWorkState ()>>& doWorkers);
                                                         ^~
make[2]: *** [src/support/CMakeFiles/support.dir/threads.cpp.o] Error 1
make[1]: *** [src/support/CMakeFiles/support.dir/all] Error 2
make[2]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/parser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/achala/GIT/mir2wasm/binaryen/src/emscripten-optimizer/optimizer-shared.cpp: In function ‘AsmSign detectSign(cashew::Ref, cashew::IString)’:
/home/achala/GIT/mir2wasm/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:157:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         if (op == TRSHIFT) return ASM_UNSIGNED;
         ^~
/home/achala/GIT/mir2wasm/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:160:7: note: here
       case '|': case '&': case '^': case '<': case '=': case '!': return ASM_SIGNED;
       ^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o] Error 1
make[1]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/all] Error 2
make: *** [all] Error 2
thread '<unnamed>' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/achala/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.33/src/lib.rs:773:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', libcore/result.rs:945:5
